/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estoque;

public class App {

    public static void main(String[] args) {

        Estoque est = new Estoque();

        est.adicionarProdutos("Celular", 2);
        est.adicionarProdutos("Celular", 3);

        est.consultarQuantidade("Celular");
        est.consultarQuantidade("Computador");

        est.produtoMaisEstocado();

        est.removerProdutos("Celular", 1);
        est.consultarQuantidade("Celular");
        est.consultarQuantidade("Computador");

        est.adicionarProdutos("Celular", 2);
        est.consultarQuantidade("Celular");
        est.consultarQuantidade("Computador");

        est.limparEstoque();

    }

}
